name: DeltaCraft
version: 1.0
main: eu.quantumsociety.DeltaCraft.DeltaCraft
commands:
  sethome:
    description: Bla bla bla
    usage: /sethome
  home:
    description: Bla bla bla
    usage: /home
  c:
    description: Bla bla bla
    usage: /c
  kelp:
    description: Aaaa
    usage: /kelp
permissions:
  delta.*:
    default: op
    children:
      delta.spectate.*:
        default: op
        children:
          delta.spectate.use:
            description: Test
            default: op
          delta.spectate.unlimiteddistance:
            description: Test
            default: op
      delta.kelp.*:
        default: op
        children:
          delta.kelp.use:
            description: Test
            default: op
          delta.kelp.create:
            description: Test
            default: op
          delta.kelp.remove:
            description: Test
            default: op

