name: DeltaCraft
version: 1.0
main: eu.quantumsociety.DeltaCraft.DeltaCraft
commands:
  sethome:
    description: Bla bla bla
    usage: /sethome
  home:
    description: Bla bla bla
    usage: /home
  c:
    description: Bla bla bla
    usage: /c
permissions:
  delta.*:
    default: op
    children:
      spectate.*:
        default: op
        children:
          use:
            description: Test
            default: op
          unlimiteddistance:
            description: Test
            default: op

