name: DeltaCraft
version: 1.0
main: eu.quantumsociety.deltacraft.DeltaCraft
api-version: 1.16
commands:
  sethome:
    description: Set new home
    usage: /sethome <name>
  home:
    description: Teleport home
    usage: /home <name>
  homes:
    description: List all homes
    usage: /homes
  delhome:
    description: Delete home
    usage: /delhome <name>
  c:
    description: Bla bla bla
    usage: /c
  kelp:
    description: Aaaa
    usage: /kelp
permissions:
  delta.*:
    default: op
    children:
      delta.home.*:
        default: op
        children:
          delta.home.set:
            description: Set home
            default: op
          delta.home.use:
            description: Teleport to home
            default: op
          delta.home.list.*:
            default: op
            children:
              self:
                description: List own homes
                default: op
              all:
                description: List anyones homes
                default: op
      delta.spectate.*:
        default: op
        children:
          delta.spectate.use:
            description: Test
            default: op
          delta.spectate.unlimited:
            description: Test
            default: op
      delta.kelp.*:
        default: op
        children:
          delta.kelp.use:
            description: Test
            default: op
          delta.kelp.create:
            description: Test
            default: op
          delta.kelp.setage:
            description: Test
            default: op
          delta.kelp.remove:
            description: Test
            default: op

