name: DeltaCraft
version: 1.0
main: eu.quantumsociety.DeltaCraft.DeltaCraft
commands:
  sethome:
    description: Set new home
    usage: /sethome <name>
  home:
    description: Teleport home
    usage: /home <name>
  homes:
    description: List all homes
    usage: /homes
  c:
    description: Bla bla bla
    usage: /c
  kelp:
    description: Aaaa
    usage: /kelp
permissions:
  delta.*:
    default: op
    children:
      home.*:
        default: op
        children:
          set:
            description: Set home
            default: op
          use:
            description: Teleport to home
            default: op
          list.*:
            default: op
            children:
              self:
                description: List own homes
                default: op
              all:
                description: List anyones homes
                default: op
      spectate.*:
        default: op
        children:
          delta.spectate.use:
            description: Test
            default: op
          delta.spectate.unlimiteddistance:
            description: Test
            default: op
      delta.kelp.*:
        default: op
        children:
          delta.kelp.use:
            description: Test
            default: op
          delta.kelp.create:
            description: Test
            default: op
          delta.kelp.remove:
            description: Test
            default: op

