name: DeltaCraft
version: 1.0.3
main: eu.quantumsociety.deltacraft.DeltaCraft
api-version: 1.16
authors: [koudy008 (Karel Koudelka), Fjarik (Jiří Falta)]
website: deltacraft.eu
commands:
  sethome:
    description: Set new home
    usage: /sethome <name>
  home:
    description: Teleport home
    usage: /home <name>
  homes:
    description: List all homes
    usage: /homes
  delhome:
    description: Delete home
    usage: /delhome <name>
  c:
    description: Switch to/from spectating gamemode
    usage: /c
  kelp:
    description: Kelp farms
    usage: /kelp ?
  kahy:
    description: Protection against kahy
    usage: /kahy
  inv:
    description: Invisible item frames
    usage: /inv
    aliases: [frame, itemframe]
permissions:
  delta.*:
    default: op
    children:
      delta.home.*:
        default: op
        children:
          delta.home.set:
            description: Set home
            default: true
          delta.home.use:
            description: Teleport to home
            default: true
          delta.home.delete:
            description: Delete home
            default: true
          delta.home.list.*:
            default: op
            children:
              delta.home.list.self:
                description: List own homes
                default: true
              delta.home.list.all:
                description: List anyones homes
                default: op
      delta.spectate.*:
        default: op
        children:
          delta.spectate.use:
            description: Use spectate
            default: true
          delta.spectate.unlimited:
            description: Has unlimited spectate range
            default: op
      delta.kelp.*:
        default: op
        children:
          delta.kelp.use:
            description: Use kelp farms
            default: true
          delta.kelp.create:
            description: Create kelp farm
            default: true
          delta.kelp.setage:
            description: Set age of a kelp
            default: op
          delta.kelp.remove:
            description: Remove kelp farm
            default: true
      delta.kahy.*:
        default: op
        children:
          delta.kahy.use:
            description: Use protection against kahy
            default: true
      delta.frame.*:
        default: op
        children:
          delta.frame.use:
            description: Switch visibility of item frame
            default: true
